version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: androidx
  ignore:
  - dependency-name: com.squareup.leakcanary:leakcanary-android
    versions:
    - "2.5"
    - "2.6"
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
